name: Go Setup
description: Setup Go for testing and compilation.
runs:
  using: composite
  steps:
    # We don't have any deps, so skip go.sum as a hash.
    # Use the week number to ensure cache is updated weekly.
    - name: Date
      id: date
      run: |
        date -u "+week-number=week-%U" >> $GITHUB_OUTPUT
      shell: bash

    - name: Go build cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
        key: go-build-${{ runner.os }}-${{ runner.arch }}-${{ steps.date.outputs.week-number }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: setup Go
      shell: bash
      run: ${GITHUB_WORKSPACE}/.github/actions/go_setup/go.sh
