name: Lint
on: push
jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: ./.github/actions/go_setup

      - name: Run
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.5
