name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: ./.github/actions/go_setup

      - run: go test -race ./...

  fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: ./.github/actions/go_setup

      - name: FuzzLifecycle
        run: go test -fuzztime 15s -fuzz=FuzzLifecycle ./trace

      - name: FuzzParseState
        run: go test -fuzztime 15s -fuzz=FuzzParseState ./trace
